# Set to true to use lowercase keywords instead of uppercase.
lowercaseKeywords: false
connections:
  - alias: test
    driver: sqlite3
    dataSourceName: C:/Users/fryta/Pulpit/desk/Important/Programming Projects/Millionaires/server/millionaires.db
